# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 807a9128babb7afeedd31e74132d839808135c9e75d4e2e7bef8b776ad0c3dcdcce82f2558d75b6aa63fa1a2bf2e8c941b3df8d0f0f9fd867ab72094cb1510a1

test:
  secret_key_base: cb211e19d2a73490f3bebea9944af5a553b913b0bb2a0a45679f74c7e06595dbccc88fc3d64d69a7199f27e15aa3dc9fd936a5d9050f2666dbe608acfbede323

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
